services:
  - type: web
    name: resume-screening-api
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: OPENAI_API_KEY
        value: your_api_key_here  # <-- replace with your real OpenAI key
    plan: free
